name: 'Workflow run conclusion dispatch action'
description: 'For use in a workflow run.  Create a dispatch event to be used in a repository_dispatch workflow. Event is `${workflowName} - ${conclusion}` and client_payload is the workflow run payload.'
author: 'Tony Hallett'
inputs:
  GITHUB_PAT:
    required: true
    description: 'Github Personal Access Token - https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token'
runs:
  using: 'node12'
  main: 'dist/index.js'
